/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formularioNuevaVenta.java
 *
 * Created on 9/04/2012, 04:45:36 PM
 */

package zapateria.vista;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import javax.swing.JOptionPane;
import zapateria.controlador.Conexion;
import zapateria.controlador.Sistema;
import zapateria.modelo.Cliente;
import zapateria.modelo.Venta;
import zapateria.modelo.Zapato;

/**
 *
 * @author ABAD
 */
public class formularioNuevaVenta extends javax.swing.JFrame {
    
    /** Creates new form formularioNuevaVenta */
    
    public formularioNuevaVenta() {
        
        Calendar fecha=Calendar.getInstance();
        Conexion cnx=new Conexion();
        Connection conexion;
        java.sql.Statement consultar;
        int id = 0;
        try{
            conexion=cnx.getConexion();
            consultar=conexion.createStatement();
            ResultSet resultado=consultar.executeQuery("Select * from venta");
            while(resultado.next()){
                id=resultado.getInt("id_venta");
            }
            conexion.close();
            consultar.close();
            resultado.close();
        }catch(SQLException sql){
        }
        Venta v=new Venta();
        v.setFecha(fecha);
        initComponents();
        this.cIdVenta.setText(Integer.toString(id+1));
        this.cFechaVenta.setText(v.obtenerFechaI());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bGuardarVenta = new javax.swing.JButton();
        bCancelarVenta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cIdVenta = new javax.swing.JTextField();
        cFechaVenta = new javax.swing.JTextField();
        cRFCVenta = new javax.swing.JTextField();
        cNombreVenta = new javax.swing.JTextField();
        cDireccionVenta = new javax.swing.JTextField();
        cIdZapatoVenta = new javax.swing.JTextField();
        cTotalVenta = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        cColorZapatoVenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cTallaZapatoVenta = new javax.swing.JTextField();
        cMarcaZapatoVenta = new javax.swing.JTextField();
        cCantidadZapatosVenta = new javax.swing.JTextField();
        cPrecioZapatoVenta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ANDREA S.A de C.V.");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bGuardarVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bGuardarVenta.setForeground(new java.awt.Color(255, 0, 0));
        bGuardarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoGuardar.png"))); // NOI18N
        bGuardarVenta.setText("GUARDAR");
        bGuardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarVentaActionPerformed(evt);
            }
        });

        bCancelarVenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        bCancelarVenta.setForeground(new java.awt.Color(255, 0, 0));
        bCancelarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/tachee.png"))); // NOI18N
        bCancelarVenta.setText("CANCELAR");
        bCancelarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarVentaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("REALIZAR VENTA");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ID VENTA:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("FECHA:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("RFC:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("DIRECCION:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("DATOS DEL CLIENTE");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("NOMBRE:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("DESCRIPCION DE VENTA");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("ID ZAPATO:");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("TOTAL DE VENTA:");

        cIdVenta.setBackground(new java.awt.Color(255, 255, 255));
        cIdVenta.setEditable(false);

        cFechaVenta.setBackground(new java.awt.Color(255, 255, 255));
        cFechaVenta.setEditable(false);

        cRFCVenta.setBackground(new java.awt.Color(204, 204, 204));
        cRFCVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cRFCVentaActionPerformed(evt);
            }
        });
        cRFCVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cRFCVentaFocusLost(evt);
            }
        });

        cNombreVenta.setBackground(new java.awt.Color(255, 255, 255));
        cNombreVenta.setEditable(false);

        cDireccionVenta.setBackground(new java.awt.Color(255, 255, 255));
        cDireccionVenta.setEditable(false);

        cIdZapatoVenta.setBackground(new java.awt.Color(204, 204, 204));
        cIdZapatoVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cIdZapatoVentaFocusLost(evt);
            }
        });

        cTotalVenta.setBackground(new java.awt.Color(255, 255, 255));
        cTotalVenta.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("COLOR:");

        cColorZapatoVenta.setBackground(new java.awt.Color(255, 255, 255));
        cColorZapatoVenta.setEditable(false);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("TALLA:");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("MARCA:");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("CANTIDAD:");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("PRECIO UNITARIO:");

        cTallaZapatoVenta.setBackground(new java.awt.Color(255, 255, 255));
        cTallaZapatoVenta.setEditable(false);

        cMarcaZapatoVenta.setBackground(new java.awt.Color(255, 255, 255));
        cMarcaZapatoVenta.setEditable(false);

        cCantidadZapatosVenta.setBackground(new java.awt.Color(204, 204, 204));
        cCantidadZapatosVenta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cCantidadZapatosVentaFocusLost(evt);
            }
        });

        cPrecioZapatoVenta.setBackground(new java.awt.Color(255, 255, 255));
        cPrecioZapatoVenta.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cDireccionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cRFCVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cNombreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cCantidadZapatosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cPrecioZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cIdZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cTallaZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cMarcaZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cColorZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel16))
                            .addComponent(bCancelarVenta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bGuardarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(115, 115, 115))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cFechaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cRFCVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNombreVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDireccionVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cIdZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cColorZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTallaZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cMarcaZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cCantidadZapatosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cPrecioZapatoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTotalVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCancelarVenta))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bCancelarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarVentaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new menuPrincipal().setVisible(true);
    }//GEN-LAST:event_bCancelarVentaActionPerformed

    private void bGuardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarVentaActionPerformed
        // TODO add your handling code here:
        int i=0,iRes;
        if(this.cCantidadZapatosVenta.getText().equals("")){
            i++;
        }else;
        if(this.cTotalVenta.getText().equals("")){
            i++;
        }else;
        if(i==0){
            Venta v=new Venta();
            v.setIdVenta(Integer.parseInt(this.cIdVenta.getText()));
            Cliente c=new Cliente();
            c.setRFC(this.cRFCVenta.getText());
            v.setCliente(c);
            Zapato z=new Zapato();
            z.setidZapato(Integer.parseInt(this.cIdZapatoVenta.getText()));
            v.setZapato(z);
            v.setCantidad(Integer.parseInt(this.cCantidadZapatosVenta.getText()));
            v.setTotalVenta(Float.parseFloat(this.cTotalVenta.getText()));
            Calendar fecha1=Calendar.getInstance();
            v.setFecha(fecha1);
            iRes=new Sistema().nuevaVenta(v);
            if(iRes==0){
                JOptionPane.showMessageDialog(this,"Los datos fueron guardados correctamente");
                this.setVisible(false);
                new menuPrincipal().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this,"Ocurrio un error mientras se guardaban los datos");
            }
        }else{
            JOptionPane.showMessageDialog(this,"Faltan campos por llenar");
    }
        
    }//GEN-LAST:event_bGuardarVentaActionPerformed

    private void cRFCVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cRFCVentaActionPerformed
        // TODO add your handling code here:
        String rfc;
        rfc=this.cRFCVenta.getText();
        if(rfc.equals("")){
    }else{
            Cliente c=new Cliente();
            Cliente cRes=new Cliente();
            c.setRFC(rfc);
            cRes=new Sistema().consultarCliente(c);
            if(cRes.getRFC()==null){
                JOptionPane.showMessageDialog(this,"El cliente con RFC: "+c.getRFC()+" no esta dado de alta");
                this.cRFCVenta.setText(null);
            }else{
                this.cNombreVenta.setText(cRes.getNombre());
                this.cDireccionVenta.setText(cRes.getDireccion());
                
            }
        }
        
    }//GEN-LAST:event_cRFCVentaActionPerformed

    private void cIdZapatoVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cIdZapatoVentaFocusLost
        // TODO add your handling code here:
        int id_zapato;
        if(this.cIdZapatoVenta.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Ingresa un ID de ZAPATO");
        }else{
            try{
                id_zapato=Integer.parseInt(this.cIdZapatoVenta.getText());
                Zapato z=new Zapato();
                z.setidZapato(id_zapato);
                Zapato zRes=new Zapato();
                zRes=new Sistema().buscarZapato(z);
                if(zRes.getidZapato()==0){
                    JOptionPane.showMessageDialog(this,"El zapato con ID: "+id_zapato+" no esta dado de alta");
                    this.cIdZapatoVenta.setText(null);
                }else{
                    this.cColorZapatoVenta.setText(zRes.getColor());
                    this.cMarcaZapatoVenta.setText(zRes.getMarca());
                    this.cTallaZapatoVenta.setText(Float.toString(zRes.getTalla()));
                    this.cPrecioZapatoVenta.setText(Float.toString(zRes.getPrecio()));
                }
            }catch(NumberFormatException nFEx){
                JOptionPane.showMessageDialog(this,"El id debe ser un valor numerico");
                this.cIdZapatoVenta.setText(null);
            }
        }   
    }//GEN-LAST:event_cIdZapatoVentaFocusLost

    private void cCantidadZapatosVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cCantidadZapatosVentaFocusLost
        // TODO add your handling code here:
        int cantidad;
        float total,precio;
        
        if(this.cCantidadZapatosVenta.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Debe ingresar un numero de pares ");
        }else{
            try{
                cantidad=Integer.parseInt(this.cCantidadZapatosVenta.getText());
                if(this.cPrecioZapatoVenta.getText().equals("")){
                    JOptionPane.showMessageDialog(this,"El campo de PRECIO UNITARIO no ha sido llenado");
                }else{
                    precio=Float.parseFloat(this.cPrecioZapatoVenta.getText());
                    total=precio*cantidad;
                    this.cTotalVenta.setText(Float.toString(total));
                }
            }catch(NumberFormatException n){
                JOptionPane.showMessageDialog(this,"La cantidad debe ser un valor entero");
                this.cCantidadZapatosVenta.setText(null);
            }
        }
    }//GEN-LAST:event_cCantidadZapatosVentaFocusLost

    private void cRFCVentaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cRFCVentaFocusLost
        // TODO add your handling code here:
          String rfc;
        rfc=this.cRFCVenta.getText();
        if(rfc.equals("")){
    }else{
            Cliente c=new Cliente();
            Cliente cRes=new Cliente();
            c.setRFC(rfc);
            cRes=new Sistema().consultarCliente(c);
            if(cRes.getRFC()==null){
                JOptionPane.showMessageDialog(this,"El cliente con RFC: "+c.getRFC()+" no esta dado de alta");
            }else{
                this.cNombreVenta.setText(cRes.getNombre());
                this.cDireccionVenta.setText(cRes.getDireccion());
                
            }
        }
    }//GEN-LAST:event_cRFCVentaFocusLost

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioNuevaVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarVenta;
    private javax.swing.JButton bGuardarVenta;
    private javax.swing.JTextField cCantidadZapatosVenta;
    private javax.swing.JTextField cColorZapatoVenta;
    private javax.swing.JTextField cDireccionVenta;
    private javax.swing.JTextField cFechaVenta;
    private javax.swing.JTextField cIdVenta;
    private javax.swing.JTextField cIdZapatoVenta;
    private javax.swing.JTextField cMarcaZapatoVenta;
    private javax.swing.JTextField cNombreVenta;
    private javax.swing.JTextField cPrecioZapatoVenta;
    private javax.swing.JTextField cRFCVenta;
    private javax.swing.JTextField cTallaZapatoVenta;
    private javax.swing.JTextField cTotalVenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
