/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formularioAñadirZapato.java
 *
 * Created on 9/04/2012, 03:10:52 PM
 */

package zapateria.vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import zapateria.controlador.Conexion;
import zapateria.controlador.Sistema;
import zapateria.modelo.Zapato;

/**
 *
 * @author ABAD
 */
public class formularioAñadirZapato extends javax.swing.JFrame {

    /** Creates new form formularioAñadirZapato */
    public formularioAñadirZapato() {
        Conexion c=new Conexion();
        Connection conexion;
        PreparedStatement declaracion;
        ResultSet res;
        int id = 0;
        try{
            conexion=c.getConexion();
            declaracion=conexion.prepareStatement("SELECT id_zapato FROM zapato");
            res=declaracion.executeQuery();
            while(res.next()){
                id=res.getInt("id_zapato");
            }
            
        }catch(SQLException esqlex){
            System.out.println(esqlex.getMessage());
        }
        initComponents();  
        this.cIdZapatoAgregarZapato.setText(Integer.toString(id+1));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bGuardarAgregarZapato = new javax.swing.JButton();
        botonCancelarAgregarZapato = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cIdZapatoAgregarZapato = new javax.swing.JTextField();
        cColorAgregarZapato = new javax.swing.JTextField();
        cModeloAgregarZapato = new javax.swing.JTextField();
        cMarcaAgregarZapato = new javax.swing.JTextField();
        cTallaAgregarZapato = new javax.swing.JTextField();
        cCantidadAgregarZapato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ANDREA S.A. de C.V.");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bGuardarAgregarZapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoGuardar.png"))); // NOI18N
        bGuardarAgregarZapato.setText("GUARDAR");
        bGuardarAgregarZapato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarAgregarZapatoActionPerformed(evt);
            }
        });

        botonCancelarAgregarZapato.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/tachee.png"))); // NOI18N
        botonCancelarAgregarZapato.setText("CANCELAR");
        botonCancelarAgregarZapato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarAgregarZapatoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("AGREGAR ZAPATO");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("ID ZAPATO:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("MODELO:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("COLOR:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("TALLA:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("MARCA:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("PARES DISPONIBLES:");

        cIdZapatoAgregarZapato.setBackground(java.awt.Color.white);
        cIdZapatoAgregarZapato.setEditable(false);
        cIdZapatoAgregarZapato.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cColorAgregarZapato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cColorAgregarZapatoActionPerformed(evt);
            }
        });
        cColorAgregarZapato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cColorAgregarZapatoKeyTyped(evt);
            }
        });

        cModeloAgregarZapato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cModeloAgregarZapatoKeyTyped(evt);
            }
        });

        cMarcaAgregarZapato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cMarcaAgregarZapatoKeyTyped(evt);
            }
        });

        cTallaAgregarZapato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cTallaAgregarZapatoKeyTyped(evt);
            }
        });

        cCantidadAgregarZapato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cCantidadAgregarZapatoKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("PRECIO:");

        cPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPrecioKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cIdZapatoAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cColorAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cModeloAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cMarcaAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(botonCancelarAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cCantidadAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bGuardarAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cTallaAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cIdZapatoAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cColorAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cModeloAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cMarcaAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTallaAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cCantidadAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 194, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bGuardarAgregarZapato, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCancelarAgregarZapato))
                        .addGap(48, 48, 48))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarAgregarZapatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarAgregarZapatoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new menuPrincipal().setVisible(true);
    }//GEN-LAST:event_botonCancelarAgregarZapatoActionPerformed

    private void cColorAgregarZapatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cColorAgregarZapatoKeyTyped
        // TODO add your handling code here:
        if( ! this.cColorAgregarZapato.getText( ).matches("[a-z A-z ñ]*" ) ){
            JOptionPane.showMessageDialog(this,"No se permiten valores numericos");
            this.cColorAgregarZapato.setText(null);
        }
    }//GEN-LAST:event_cColorAgregarZapatoKeyTyped

    private void cModeloAgregarZapatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cModeloAgregarZapatoKeyTyped
        // TODO add your handling code here:
        if( ! this.cModeloAgregarZapato.getText( ).matches("[a-z A-z ñ]*" ) ){
            JOptionPane.showMessageDialog(this,"No se permiten valores numericos");
            this.cModeloAgregarZapato.setText(null);
        }
    }//GEN-LAST:event_cModeloAgregarZapatoKeyTyped

    private void bGuardarAgregarZapatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarAgregarZapatoActionPerformed
        // TODO add your handling code here:
        int conta=0,regresa=0;
        String disponobilidad,tall;
        Zapato z=new Zapato();
        if(this.cModeloAgregarZapato.getText().isEmpty()){
            conta++;
        }else{
        z.setModelo(this.cModeloAgregarZapato.getText());
        }
        if(this.cTallaAgregarZapato.getText().isEmpty()){
            conta++;
        }else{
        z.setTalla(Float.parseFloat(this.cTallaAgregarZapato.getText()));
        }
        z.setColor(this.cColorAgregarZapato.getText());
        if(z.getColor().isEmpty()){
            conta++;
        }else;
        z.setMarca(this.cMarcaAgregarZapato.getText());
        if(z.getMarca().isEmpty()){
            conta++;
        }
        if(this.cCantidadAgregarZapato.getText().isEmpty()){
            conta++;
            
        }else{
        z.setCantidadz(Integer.parseInt(this.cCantidadAgregarZapato.getText()));
        }
        if(this.cPrecio.getText().isEmpty()){
            conta++;
        }else{
            z.setPrecio(Float.parseFloat(this.cPrecio.getText()));
        }
        if(conta==0){
            z.setidZapato(Integer.parseInt(this.cIdZapatoAgregarZapato.getText()));
            System.out.println(z.getidZapato()+z.getModelo()+z.getColor()+z.getTalla()+z.getMarca()+z.getCantidadz());
            regresa=new Sistema().añadirZapato(z);
            if(regresa==1){
                JOptionPane.showMessageDialog(this,"Los datos han sido guardados");
                this.setVisible(false);
                new menuPrincipal().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(this,"Error de conexion");
            }
            
        }else{
            JOptionPane.showMessageDialog(this,"Faltan campos por llenar");
        }
        
    }//GEN-LAST:event_bGuardarAgregarZapatoActionPerformed

    private void cColorAgregarZapatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cColorAgregarZapatoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cColorAgregarZapatoActionPerformed

    private void cTallaAgregarZapatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTallaAgregarZapatoKeyTyped
        // TODO add your handling code here:
        if( ! this.cTallaAgregarZapato.getText( ).matches( "[. 0-9]*") ){
            JOptionPane.showMessageDialog(this,"Valor no numerico");
            this.cTallaAgregarZapato.setText(null);
        }
    }//GEN-LAST:event_cTallaAgregarZapatoKeyTyped

    private void cCantidadAgregarZapatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cCantidadAgregarZapatoKeyTyped
        // TODO add your handling code here:
        if( ! this.cCantidadAgregarZapato.getText( ).matches( "[0-9]*" ) ){
            JOptionPane.showMessageDialog(this,"Valor no numerico");
            this.cCantidadAgregarZapato.setText(null);
        }
    }//GEN-LAST:event_cCantidadAgregarZapatoKeyTyped

    private void cPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPrecioKeyTyped
        // TODO add your handling code here:
        if( ! this.cPrecio.getText( ).matches( "[. 0-9]*") ){
            JOptionPane.showMessageDialog(this,"Valor no numerico");
            this.cPrecio.setText(null);
        }
    }//GEN-LAST:event_cPrecioKeyTyped

    private void cMarcaAgregarZapatoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cMarcaAgregarZapatoKeyTyped
        // TODO add your handling code here:
        if( ! this.cMarcaAgregarZapato.getText( ).matches("[a-z A-z ñ]*" ) ){
            JOptionPane.showMessageDialog(this,"No se permiten valores numericos");
            this.cMarcaAgregarZapato.setText(null);
        }
    }//GEN-LAST:event_cMarcaAgregarZapatoKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioAñadirZapato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarAgregarZapato;
    private javax.swing.JButton botonCancelarAgregarZapato;
    private javax.swing.JTextField cCantidadAgregarZapato;
    private javax.swing.JTextField cColorAgregarZapato;
    private javax.swing.JTextField cIdZapatoAgregarZapato;
    private javax.swing.JTextField cMarcaAgregarZapato;
    private javax.swing.JTextField cModeloAgregarZapato;
    private javax.swing.JTextField cPrecio;
    private javax.swing.JTextField cTallaAgregarZapato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
