/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * formularioNuevoCliente.java
 *
 * Created on 9/04/2012, 02:20:52 PM
 */

package zapateria.vista;

import javax.swing.JOptionPane;
import zapateria.controlador.Sistema;
import zapateria.modelo.Cliente;

/**
 *
 * @author ABAD
 */
public class formularioNuevoCliente extends javax.swing.JFrame {

    /** Creates new form formularioNuevoCliente */
    public formularioNuevoCliente() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botonCancelarNuevoCliente = new javax.swing.JButton();
        bGuardarNuevoCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cRfcNuevoCliente = new javax.swing.JTextField();
        cNombreNuevoCliente = new javax.swing.JTextField();
        cApellidosNuevoCliente = new javax.swing.JTextField();
        cTelefonoNuevoCliente = new javax.swing.JTextField();
        cDireccionNuevoCliente = new javax.swing.JTextField();
        cEmailNuevoCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("ANDREA S.A. de C.V.");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        botonCancelarNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/tachee.png"))); // NOI18N
        botonCancelarNuevoCliente.setText("CANCELAR");
        botonCancelarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarNuevoClienteActionPerformed(evt);
            }
        });

        bGuardarNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoGuardar.png"))); // NOI18N
        bGuardarNuevoCliente.setText("GUARDAR");
        bGuardarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarNuevoClienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("NUEVO CLIENTE");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("RFC:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("NOMBRE (S):");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("APELLIDOS:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("TELEFONO:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("DIRECCION:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("E-MAIL:");

        cNombreNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cNombreNuevoClienteActionPerformed(evt);
            }
        });
        cNombreNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNombreNuevoClienteKeyTyped(evt);
            }
        });

        cApellidosNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cApellidosNuevoClienteKeyTyped(evt);
            }
        });

        cTelefonoNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cTelefonoNuevoClienteKeyTyped(evt);
            }
        });

        cEmailNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cEmailNuevoClienteKeyTyped(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoAgregar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(botonCancelarNuevoCliente)
                .addGap(46, 46, 46)
                .addComponent(bGuardarNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addGap(63, 63, 63))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(40, 40, 40))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cEmailNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cDireccionNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cTelefonoNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cApellidosNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cRfcNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cNombreNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cRfcNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNombreNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cApellidosNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTelefonoNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cDireccionNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cEmailNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelarNuevoCliente)
                    .addComponent(bGuardarNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarNuevoClienteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new menuPrincipal().setVisible(true);
    }//GEN-LAST:event_botonCancelarNuevoClienteActionPerformed

    private void bGuardarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarNuevoClienteActionPerformed
        // TODO add your handling code here:
        int res,i=0;
        String tel;
        Cliente c=new Cliente();
        c.setRFC(this.cRfcNuevoCliente.getText());
        if(c.getRFC().isEmpty()){
             JOptionPane.showMessageDialog(this, "Ingrese el RFC del cliente");
             i++;
        }else;
        c.setNombre(this.cNombreNuevoCliente.getText());
        if(c.getNombre().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese al NOMBRE de cliente");
            i++;
        } else; 
        c.setApellidos(this.cApellidosNuevoCliente.getText());
        if(c.getApellidos().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese los APELLIDOS del cliente");
            i++;
        } else; 
        c.setDireccion(this.cDireccionNuevoCliente.getText());
        if(c.getDireccion().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese la DIRECCION de cliente");
            i++;
        } else; 
        c.setEmail(this.cEmailNuevoCliente.getText());
        if(c.getEmail().isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese eL EMAIL de cliente");
            i++;
        } else; 
        tel=this.cTelefonoNuevoCliente.getText();
        if(tel.isEmpty()){
            JOptionPane.showMessageDialog(this,"Ingrese el TELEFONO del cliente");
            i++;
        } else{ 
        c.setTelefono(Integer.parseInt(tel));
        }
        
        if(i==0){
            res=new Sistema().nuevoCliente(c);
            if(res==0){
                JOptionPane.showMessageDialog(this,"Los datos se guardaron correctamente");
                this.setVisible(false);
                new menuPrincipal().setVisible(true);
            
            }else{
                JOptionPane.showMessageDialog(this,"Error: Ese RFC ya fue dado de alta");
            }
        }else;                
    }//GEN-LAST:event_bGuardarNuevoClienteActionPerformed

    private void cNombreNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNombreNuevoClienteKeyTyped
        // TODO add your handling code here:
        if( ! this.cNombreNuevoCliente.getText( ).matches("[a-zA-z- -ñ-]*" ) ){
            JOptionPane.showMessageDialog(this,"No se permiten valores numericos");
            this.cNombreNuevoCliente.setText(null);
        }
    }//GEN-LAST:event_cNombreNuevoClienteKeyTyped

    private void cEmailNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cEmailNuevoClienteKeyTyped
        // TODO add your handling code here:
        if( ! this.cEmailNuevoCliente.getText( ).matches( "[a-z@.A-Z 0-9_]*" ) ){
            JOptionPane.showMessageDialog(this,"Verifica que este bien escrito el E-MAIL");
        }
    }//GEN-LAST:event_cEmailNuevoClienteKeyTyped

    private void cTelefonoNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cTelefonoNuevoClienteKeyTyped
        // TODO add your handling code here:
        if( ! this.cTelefonoNuevoCliente.getText( ).matches( "[0-9]*" ) ){
            JOptionPane.showMessageDialog(this,"Valor no numerico");
            this.cTelefonoNuevoCliente.setText(null);
        }
    }//GEN-LAST:event_cTelefonoNuevoClienteKeyTyped

    private void cApellidosNuevoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cApellidosNuevoClienteKeyTyped
        // TODO add your handling code here:
        if( ! this.cApellidosNuevoCliente.getText( ).matches("[a-zA-z- -ñ-]*" ) ){
            JOptionPane.showMessageDialog(this,"No se permiten valores numericos");
            this.cApellidosNuevoCliente.setText(null);
        }
    }//GEN-LAST:event_cApellidosNuevoClienteKeyTyped

    private void cNombreNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cNombreNuevoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cNombreNuevoClienteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioNuevoCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bGuardarNuevoCliente;
    private javax.swing.JButton botonCancelarNuevoCliente;
    private javax.swing.JTextField cApellidosNuevoCliente;
    private javax.swing.JTextField cDireccionNuevoCliente;
    private javax.swing.JTextField cEmailNuevoCliente;
    private javax.swing.JTextField cNombreNuevoCliente;
    private javax.swing.JTextField cRfcNuevoCliente;
    private javax.swing.JTextField cTelefonoNuevoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
