/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * principal.java
 *
 * Created on 9/04/2012, 02:01:33 PM
 */

package zapateria.vista;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import zapateria.controlador.Sistema;
import zapateria.modelo.Cliente;
import zapateria.modelo.Proveedor;
import zapateria.modelo.Venta;
import zapateria.modelo.Zapato;

/**
 *
 * @author ABAD
 */
public class menuPrincipal extends javax.swing.JFrame {

    /** Creates new form principal */
    public menuPrincipal() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        archivoSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        usuarioCuenta = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        usuarioEliminar = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuNuevoProveedor = new javax.swing.JMenuItem();
        proveedorConsultar = new javax.swing.JMenuItem();
        modificarProveedor = new javax.swing.JMenuItem();
        eliminarProveedor = new javax.swing.JMenuItem();
        menuZapatos = new javax.swing.JMenu();
        zapatosAñadir = new javax.swing.JMenuItem();
        zapatosBuscar = new javax.swing.JMenuItem();
        zapatosModificar = new javax.swing.JMenuItem();
        zapatosEliminar = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        clientesNuevo = new javax.swing.JMenuItem();
        clientesConsultar = new javax.swing.JMenuItem();
        clientesModificar = new javax.swing.JMenuItem();
        clientesEliminar = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        ventasNueva = new javax.swing.JMenuItem();
        ventasConsultar = new javax.swing.JMenuItem();
        ventasEliminar = new javax.swing.JMenuItem();
        menuCaja = new javax.swing.JMenu();
        cajaCobrar = new javax.swing.JMenuItem();
        cajaCorte = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        ayudaAcercaDe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE VENTA DE CALZADO");
        setResizable(false);

        panelLogo.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/andrea.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        menuArchivo.setForeground(new java.awt.Color(255, 0, 0));
        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoArchivo2.png"))); // NOI18N
        menuArchivo.setText("Archivo");

        archivoSalir.setForeground(new java.awt.Color(255, 0, 0));
        archivoSalir.setText("Salir");
        archivoSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archivoSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(archivoSalir);

        barraMenu.add(menuArchivo);

        jMenu2.setForeground(new java.awt.Color(255, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoUsuario.png"))); // NOI18N
        jMenu2.setText("Usuario");

        jMenuItem1.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem1.setText("Cerrar sesion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        usuarioCuenta.setForeground(new java.awt.Color(255, 0, 0));
        usuarioCuenta.setText("Cuenta");
        usuarioCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioCuentaActionPerformed(evt);
            }
        });
        jMenu2.add(usuarioCuenta);

        jMenuItem3.setForeground(new java.awt.Color(255, 0, 0));
        jMenuItem3.setText("Agregar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        usuarioEliminar.setForeground(new java.awt.Color(255, 0, 0));
        usuarioEliminar.setText("Eliminar");
        usuarioEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioEliminarActionPerformed(evt);
            }
        });
        jMenu2.add(usuarioEliminar);

        barraMenu.add(jMenu2);

        jMenu1.setForeground(new java.awt.Color(255, 0, 0));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoProveedor.png"))); // NOI18N
        jMenu1.setText("Proveedor");

        menuNuevoProveedor.setForeground(new java.awt.Color(255, 0, 0));
        menuNuevoProveedor.setText("Nuevo");
        menuNuevoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(menuNuevoProveedor);

        proveedorConsultar.setForeground(new java.awt.Color(255, 0, 0));
        proveedorConsultar.setText("Consultar");
        proveedorConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorConsultarActionPerformed(evt);
            }
        });
        jMenu1.add(proveedorConsultar);

        modificarProveedor.setForeground(new java.awt.Color(255, 0, 0));
        modificarProveedor.setText("Modificar");
        modificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(modificarProveedor);

        eliminarProveedor.setForeground(new java.awt.Color(255, 0, 0));
        eliminarProveedor.setText("Eliminar");
        eliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProveedorActionPerformed(evt);
            }
        });
        jMenu1.add(eliminarProveedor);

        barraMenu.add(jMenu1);

        menuZapatos.setForeground(new java.awt.Color(255, 0, 0));
        menuZapatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoZapato1.jpg"))); // NOI18N
        menuZapatos.setText("Zapatos");

        zapatosAñadir.setForeground(new java.awt.Color(255, 0, 0));
        zapatosAñadir.setText("Añadir");
        zapatosAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapatosAñadirActionPerformed(evt);
            }
        });
        menuZapatos.add(zapatosAñadir);

        zapatosBuscar.setForeground(new java.awt.Color(255, 0, 0));
        zapatosBuscar.setText("Buscar");
        zapatosBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapatosBuscarActionPerformed(evt);
            }
        });
        menuZapatos.add(zapatosBuscar);

        zapatosModificar.setForeground(new java.awt.Color(255, 0, 0));
        zapatosModificar.setText("Modificar");
        zapatosModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapatosModificarActionPerformed(evt);
            }
        });
        menuZapatos.add(zapatosModificar);

        zapatosEliminar.setForeground(new java.awt.Color(255, 0, 0));
        zapatosEliminar.setText("Eliminar");
        zapatosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zapatosEliminarActionPerformed(evt);
            }
        });
        menuZapatos.add(zapatosEliminar);

        barraMenu.add(menuZapatos);

        menuClientes.setForeground(new java.awt.Color(255, 0, 0));
        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoCliente.png"))); // NOI18N
        menuClientes.setText("Clientes");

        clientesNuevo.setForeground(new java.awt.Color(255, 0, 0));
        clientesNuevo.setText("Nuevo");
        clientesNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesNuevoActionPerformed(evt);
            }
        });
        menuClientes.add(clientesNuevo);

        clientesConsultar.setForeground(new java.awt.Color(255, 0, 0));
        clientesConsultar.setText("Consultar");
        clientesConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesConsultarActionPerformed(evt);
            }
        });
        menuClientes.add(clientesConsultar);

        clientesModificar.setForeground(new java.awt.Color(255, 0, 0));
        clientesModificar.setText("Modificar");
        clientesModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesModificarActionPerformed(evt);
            }
        });
        menuClientes.add(clientesModificar);

        clientesEliminar.setForeground(new java.awt.Color(255, 0, 0));
        clientesEliminar.setText("Eliminar");
        clientesEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesEliminarActionPerformed(evt);
            }
        });
        menuClientes.add(clientesEliminar);

        barraMenu.add(menuClientes);

        menuVentas.setForeground(new java.awt.Color(255, 0, 0));
        menuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoVenta.png"))); // NOI18N
        menuVentas.setText("Ventas");

        ventasNueva.setForeground(new java.awt.Color(255, 0, 0));
        ventasNueva.setText("Nueva");
        ventasNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasNuevaActionPerformed(evt);
            }
        });
        menuVentas.add(ventasNueva);

        ventasConsultar.setForeground(new java.awt.Color(255, 0, 0));
        ventasConsultar.setText("Consultar");
        ventasConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasConsultarActionPerformed(evt);
            }
        });
        menuVentas.add(ventasConsultar);

        ventasEliminar.setForeground(new java.awt.Color(255, 0, 0));
        ventasEliminar.setText("Cancelar");
        ventasEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasEliminarActionPerformed(evt);
            }
        });
        menuVentas.add(ventasEliminar);

        barraMenu.add(menuVentas);

        menuCaja.setForeground(new java.awt.Color(255, 0, 0));
        menuCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoCaja.png"))); // NOI18N
        menuCaja.setText("Caja");

        cajaCobrar.setForeground(new java.awt.Color(255, 0, 0));
        cajaCobrar.setText("Cobrar");
        cajaCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCobrarActionPerformed(evt);
            }
        });
        menuCaja.add(cajaCobrar);

        cajaCorte.setForeground(new java.awt.Color(255, 0, 0));
        cajaCorte.setText("Corte");
        cajaCorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaCorteActionPerformed(evt);
            }
        });
        menuCaja.add(cajaCorte);

        barraMenu.add(menuCaja);

        menuAyuda.setForeground(new java.awt.Color(255, 0, 0));
        menuAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zapateria/vista/iconoAyuda.png"))); // NOI18N
        menuAyuda.setText("Ayuda");

        ayudaAcercaDe.setForeground(new java.awt.Color(255, 0, 0));
        ayudaAcercaDe.setText("Acerda de...");
        ayudaAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayudaAcercaDeActionPerformed(evt);
            }
        });
        menuAyuda.add(ayudaAcercaDe);

        barraMenu.add(menuAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesNuevoActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new formularioNuevoCliente().setVisible(true);
}//GEN-LAST:event_clientesNuevoActionPerformed

    private void clientesConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesConsultarActionPerformed
        // TODO add your handling code here:
        String entrada;
        Cliente regresado;
        
        try{
            entrada=JOptionPane.showInputDialog(this,"Ingrese el RFC del cliente");
            if(entrada.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar una clave");
                this.clientesConsultarActionPerformed(evt);
            }else{
                    Cliente c=new Cliente();
                    c.setRFC(entrada);
                    regresado=new Sistema().consultarCliente(c);
                    //System.out.println("Ya regrese"+ regresado.getRFC());
                    if(regresado.getRFC()==null){
                         JOptionPane.showMessageDialog(this,"El cliente no se encuentra registrado");
                    }else{
                        this.setVisible(false);
                        new formularioConsultarCliente().llenarCampos(regresado);
                        
                    }
            
            }
        }catch(NullPointerException npex){            
        }
    }//GEN-LAST:event_clientesConsultarActionPerformed

    private void clientesModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesModificarActionPerformed
        // TODO add your handling code here:
         String clave;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa el RFC del cliente");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar el RFC del cliente");
                this.eliminarProveedorActionPerformed(evt);
            }else{
                Cliente c=new Cliente();
                Cliente cRes=new Cliente();
                c.setRFC(clave);
                cRes=new Sistema().consultarCliente(c);
                if(cRes.getRFC()==null){
                    JOptionPane.showMessageDialog(this,"El cliente con RFC: "+clave+" no esta dado de alta");
                }else{
                    this.setVisible(false);
                    new formularioModificarCliente().llenarCampos(cRes);
                }
                      
            }
        }catch(NullPointerException npex){
            
        }
      
    }//GEN-LAST:event_clientesModificarActionPerformed

    private void zapatosAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapatosAñadirActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new formularioAñadirZapato().setVisible(true);
    }//GEN-LAST:event_zapatosAñadirActionPerformed

    private void zapatosBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapatosBuscarActionPerformed
        // TODO add your handling code here:
        Zapato z=new Zapato();
        Zapato zRes=new Zapato();
        int codigo;
        String in;
        try{
            in=JOptionPane.showInputDialog(this,"Ingrese un codigo de Zapato");
            if(in.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingreasr un codigo de zapato");
                this.zapatosBuscarActionPerformed(evt);
            }else{
                try{
                    
                    codigo=Integer.parseInt(in);
                    z.setidZapato(codigo);
                    zRes=new Sistema().buscarZapato(z);
                    System.out.println(zRes.getidZapato());
                    if(zRes.getidZapato()!=0){
                        new formularioBuscarZapato().llenarCampos(zRes);
                        this.setVisible(false);
                        }else{
                        JOptionPane.showMessageDialog(this,"El zapato con clave: "+codigo +" no existe");
                    }
                
                }catch(NumberFormatException nbE){
                    JOptionPane.showMessageDialog(this,"La clave debe ser un valor numerico");
                }
            }
            
        }catch(NullPointerException npe){
            
        }
        //this.setVisible(false);
        //new formularioBuscarZapato().setVisible(true);
    }//GEN-LAST:event_zapatosBuscarActionPerformed

    private void zapatosModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapatosModificarActionPerformed
        // TODO add your handling code here:
         String clave;
         int id;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa un ID de zapato");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar un ID de zapato");
                this.eliminarProveedorActionPerformed(evt);
            }else{
                try{
                    Zapato z=new Zapato();
                    id=Integer.parseInt(clave);
                    z.setidZapato(id);
                    Zapato zRes=new Zapato();
                    zRes=new Sistema().buscarZapato(z);
                    if(zRes.getidZapato()==0){
                        JOptionPane.showMessageDialog(this,"El zapato con ID: "+id+" no esta dado de alta");
                    }else{
                        this.setVisible(false);
                        new formularioModificarZapato().llenarCampos(zRes);
                    }
                    
                }catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(this,"La ID debe ser un valor numerico");
                    this.eliminarProveedorActionPerformed(evt);
                }
            }
        }catch(NullPointerException npex){
            
        }
        
    }//GEN-LAST:event_zapatosModificarActionPerformed

    private void ventasNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasNuevaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new formularioNuevaVenta().setVisible(true);
    }//GEN-LAST:event_ventasNuevaActionPerformed

    private void menuNuevoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoProveedorActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        try {
            new formularioNuevoProveedor().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(menuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuNuevoProveedorActionPerformed

    private void proveedorConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorConsultarActionPerformed
        // TODO add your handling code here:
        
        Proveedor p=new Proveedor();
        Proveedor pRes;
        try{
            p.setId(Integer.parseInt(JOptionPane.showInputDialog(this,"INTRODUZCA EL ID DEL PROVEEDOR")));
            pRes=new Sistema().consultarProveedor(p);
            
            if(pRes.getId()!=0){
                this.setVisible(false);
                new formularioConsultarProveedor().llenarCampos(pRes);
            }else{
                JOptionPane.showMessageDialog(this,"El proveedor no esta dado de alta \n      INTORDUCE OTRA CLAVE");
                this.proveedorConsultarActionPerformed(evt);
            }
        }
        catch(NumberFormatException n){
            JOptionPane.showMessageDialog(this,"ERROR: Debes introducir un valor numerico");
            //this.proveedorConsultarActionPerformed(evt);
        }
    }//GEN-LAST:event_proveedorConsultarActionPerformed

    private void eliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProveedorActionPerformed
        // TODO add your handling code here:
        String clave;
        int res;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa la clave del proveedor");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar una clave de proveedor");
                this.eliminarProveedorActionPerformed(evt);
            }else{
                try{
                    Proveedor pRes=new Proveedor();
                    Proveedor p=new Proveedor();
                    p.setId(Integer.parseInt(clave));
                    pRes=new Sistema().consultarProveedor(p);
                    if(pRes.getId()==0){
                        JOptionPane.showMessageDialog(this,"ERROR: El proveedor con ID: "+clave+" no esta dado de alta");
                    }else{
                        res=new Sistema().eliminarProveedor(p);
                    if(res==0){
                        JOptionPane.showMessageDialog(this,"El proveedor con ID: "+clave+" fue eliminado");
                    }else{
                        JOptionPane.showMessageDialog(this,"ERROR: Ocurrio un error durante la eliminacion");
                    }
                    }
                    
                }catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(this,"La clave debe ser un valor numerico");
                    this.eliminarProveedorActionPerformed(evt);
                }
            }
        }catch(NullPointerException npex){
            
        }
        
        
    }//GEN-LAST:event_eliminarProveedorActionPerformed

    private void modificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarProveedorActionPerformed
        // TODO add your handling code here:
        String clave;
        int a;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa la clave del proveedor");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar una clave de proveedor");
                this.eliminarProveedorActionPerformed(evt);
            }else{
                try{
                    Proveedor p=new Proveedor();
                    Proveedor pRes=new Proveedor();
                    a=Integer.parseInt(clave);
                    p.setId(a);
                    
                    pRes=new Sistema().consultarProveedor(p);
                    if(pRes.getId()==0){
                        JOptionPane.showMessageDialog(this,"El proveedor no esta dado de alta");
                    }else{
                        this.setVisible(false);
                        new formularioModificarProveedor().llenarCampos(pRes);
                        
                    }
                }catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(this,"La clave debe ser un valor numerico");
                    this.eliminarProveedorActionPerformed(evt);
                }
            }
        }catch(NullPointerException npex){
            
        }
    }//GEN-LAST:event_modificarProveedorActionPerformed

    private void zapatosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zapatosEliminarActionPerformed
        // TODO add your handling code here:
         String clave;
         int iRegreso;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa un ID de zapato");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar un ID de zapato");
                this.zapatosEliminarActionPerformed(evt);
            }else{
                try{
                    Zapato z=new Zapato();
                    Zapato zRes=new Zapato();
                    z.setidZapato(Integer.parseInt(clave));
                    zRes=new Sistema().buscarZapato(z);
                    if(zRes.getidZapato()==0){
                        JOptionPane.showMessageDialog(this,"El zapato con ID: "+clave+" no esta dado de alta");
                    }else{
                        iRegreso=new Sistema().eliminarZapato(z);
                        if(iRegreso==0){
                            JOptionPane.showMessageDialog(this,"El zapato con ID: "+clave+" fue eliminado");
                        }else{
                            JOptionPane.showMessageDialog(this,"Error de conexion");
                        }
                        
                    }
                    
                }catch(NumberFormatException nfe){
                    JOptionPane.showMessageDialog(this,"La ID debe ser un valor numerico");
                    this.zapatosEliminarActionPerformed(evt);
                }
            }
        }catch(NullPointerException npex){
            
        }
    }//GEN-LAST:event_zapatosEliminarActionPerformed

    private void clientesEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesEliminarActionPerformed
        // TODO add your handling code here:
        String clave;
        int iRes;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa el RFC del cliente");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar el RFC del cliente");
                this.clientesEliminarActionPerformed(evt);
            }else{
                Cliente cRes=new Cliente();
                Cliente c=new Cliente();
                c.setRFC(clave);
                cRes=new Sistema().consultarCliente(c);
                if(cRes.getRFC()==null){
                    JOptionPane.showMessageDialog(this,"El cliente con RFC: "+clave +" no esta dado de alta");
                }else{
                    iRes=new Sistema().eliminarCliente(c);
                    if(iRes==0){
                        JOptionPane.showMessageDialog(this,"El cliente con RFC: "+clave+" fue eliminado");
                    }else{
                        JOptionPane.showMessageDialog(this,"Ocurrio un error en la base de datos");
                }
                }
                
            }
        }catch(NullPointerException npex){
            
        }
    }//GEN-LAST:event_clientesEliminarActionPerformed

    private void ventasConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasConsultarActionPerformed
        // TODO add your handling code here:
        String clave;
        int i;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa el RFC del cliente");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar el RFC del cliente");
                this.eliminarProveedorActionPerformed(evt);
            }else{
                Cliente c=new Cliente();
                c.setRFC(clave);
                Venta vRes=new Venta();
                Venta v=new Venta();
                v.setCliente(c);
                vRes=new Sistema().consultarVenta(v);
                if(vRes.getIdVenta()==0){
                    JOptionPane.showMessageDialog(this,"La venta no esta dada de alta");
                }else{
                    //System.out.println(vRes.getIdVenta()+vRes.getCantidad()+vRes.getCliente().getRFC()+vRes.getZapato().getidZapato());
                    this.setVisible(false);
                    new formularioConsultarVenta().llenarCampos(vRes);
                    //fcv.setVisible(true);
                }
                System.out.println("aca stoy");
            }
        }catch(NullPointerException npex){
        }
        
    }//GEN-LAST:event_ventasConsultarActionPerformed

    private void ventasEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasEliminarActionPerformed
        // TODO add your handling code here:
        String clave;
        int res;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa el RFC del cliente");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar el RFC del cliente");
                this.eliminarProveedorActionPerformed(evt);
            }else{
                Cliente c=new Cliente();
                c.setRFC(clave);
                Venta v=new Venta();
                Venta vRes=new Venta();
                v.setCliente(c);
                vRes=new Sistema().consultarVenta(v);
                if(vRes.getIdVenta()==0){
                    JOptionPane.showMessageDialog(this,"La venta con RFC de cliente: "+clave+" no esta dada de alta");
                }else{
                    res=new Sistema().eliminarVenta(vRes);
                    JOptionPane.showMessageDialog(this,"La venta fue cancelada");
                }
             }
        }catch(NullPointerException npex){
        }
    }//GEN-LAST:event_ventasEliminarActionPerformed

    private void cajaCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCobrarActionPerformed
        // TODO add your handling code here:
        String clave;
        try{
            clave=JOptionPane.showInputDialog(this,"Ingresa el RFC de cliente");
            if(clave.equals("")){
                JOptionPane.showMessageDialog(this,"Debes ingresar un RFC de cliente");
                this.eliminarProveedorActionPerformed(evt);
            }else{
                Cliente c=new Cliente();
                c.setRFC(clave);
                Venta v=new Venta();
                Venta vRes=new Venta();
                v.setCliente(c);
                vRes=new Sistema().consultarVenta(v);
                if(vRes.getIdVenta()==0){
                    JOptionPane.showMessageDialog(this,"La venta con RFC de cliente: "+clave+" no esta dada de alta");
                }else{
                    new Sistema().cobrarVenta(vRes);
                    JOptionPane.showMessageDialog(this,"Cobro realizado");
                }
            }
        }catch(NullPointerException npex){
        }
    }//GEN-LAST:event_cajaCobrarActionPerformed

    private void ayudaAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayudaAcercaDeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new formularioAcercaDe().setVisible(true);
    }//GEN-LAST:event_ayudaAcercaDeActionPerformed

    private void archivoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archivoSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_archivoSalirActionPerformed

    private void cajaCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaCorteActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Sistema().corteCaja();
    }//GEN-LAST:event_cajaCorteActionPerformed

    private void usuarioCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioCuentaActionPerformed
        // TODO add your handling code here:
        String texto;
        int id;
        try{
           texto=JOptionPane.showInputDialog(this,"Ingrese un ID de usuario"); 
           if(texto.equals("")){
               JOptionPane.showMessageDialog(this,"Debes ingresar un id de usuario");
           }else{
               try{
                    id=Integer.parseInt(texto);
                    JOptionPane.showMessageDialog(this,"EL MODULO NO DESTA DISPONIBLE");
               }catch(NumberFormatException nf){
                   JOptionPane.showMessageDialog(this,"El id debe ser un valor numerico");
                   this.usuarioCuentaActionPerformed(evt);
               }
           }
        }catch(NullPointerException npe){
            
        }
    
             
    }//GEN-LAST:event_usuarioCuentaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new formularioAgregarUsuario().setVisible(true);        ;
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void usuarioEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioEliminarActionPerformed
        // TODO add your handling code here:
         String texto;
        int id;
        try{
           texto=JOptionPane.showInputDialog(this,"Ingrese un ID de usuario"); 
           if(texto.equals("")){
               JOptionPane.showMessageDialog(this,"Debes ingresar un id de usuario");
           }else{
               try{
                    id=Integer.parseInt(texto);
                    JOptionPane.showMessageDialog(this,"EL MODULO NO DESTA DISPONIBLE");
               }catch(NumberFormatException nf){
                   JOptionPane.showMessageDialog(this,"El id debe ser un valor numerico");
                   this.usuarioEliminarActionPerformed(evt);
               }
           }
        }catch(NullPointerException npe){
            
        }
    
        
    }//GEN-LAST:event_usuarioEliminarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"ESTA ACCION NO ESTA DISPONIBLE");
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem archivoSalir;
    private javax.swing.JMenuItem ayudaAcercaDe;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenuItem cajaCobrar;
    private javax.swing.JMenuItem cajaCorte;
    private javax.swing.JMenuItem clientesConsultar;
    private javax.swing.JMenuItem clientesEliminar;
    private javax.swing.JMenuItem clientesModificar;
    private javax.swing.JMenuItem clientesNuevo;
    private javax.swing.JMenuItem eliminarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuCaja;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenuItem menuNuevoProveedor;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JMenu menuZapatos;
    private javax.swing.JMenuItem modificarProveedor;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JMenuItem proveedorConsultar;
    private javax.swing.JMenuItem usuarioCuenta;
    private javax.swing.JMenuItem usuarioEliminar;
    private javax.swing.JMenuItem ventasConsultar;
    private javax.swing.JMenuItem ventasEliminar;
    private javax.swing.JMenuItem ventasNueva;
    private javax.swing.JMenuItem zapatosAñadir;
    private javax.swing.JMenuItem zapatosBuscar;
    private javax.swing.JMenuItem zapatosEliminar;
    private javax.swing.JMenuItem zapatosModificar;
    // End of variables declaration//GEN-END:variables

}
